### ISSUE TITLE
Which zoom mod did you test it with?

### ISSUE THREAD

**Issue by eliasjurkeit** [Estecka/mc-I-See-You-Over-There#2]
I'm just curious of the "officially" tested/supported zoom mods for 1.20.1.

**Comment by Estecka** [comment]
I don't remember for sure, I don't actually use any, but I think "Logical Zoom" was one of them.

In any case, finding an incompatible mod will be a feat you really don't need to worry about.
This mod doesn't work by detecting a zoom "button" or "input", but by watching the active field of view of the camera; that data should be the end-all and be-all of every zoom mod. A funny side effect, that I think really shows how compatible it can be, is that even the effect of Slowness and Swiftness will cause small adjustments to the render distance, since they technically zoom you in and out a bit.

**Comment by Estecka** [comment]
Oh, and "Spyglass Astronomy" works too. It's not a dedicated zoom mod, but it has a custom zoom feature.

**Comment by eliasjurkeit** [comment]
Thank you! And thank you for taking the time to answer my questions. The mod's flawless btw.
